### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rakanalh** [rakanalh/django-pushy#11]
I am proposing to https://github.com/dgilland/pushjack instead of PyAPNS and Python-GCM libraries. We're going to have to test this out.

**Comment by wolfhechel** [comment]
So I've started this feature on my fork, the codebase became much cleaner but I'd like to add a feature to this though.
As it is now all push notifications are sent individually to every token, while both GCM and APNS supports batching to up to 100 devices simultaneously.

pushjack comes with batch handling OOB so I'd recommend utilizing that, it will take some more time though.

**Comment by rakanalh** [comment]
Nice! I like what you're doing so far. i've been busy the last 3 months so couldn't get the time to implement this myself. Let me know if you think we can work on this together.

**Comment by wolfhechel** [comment]
Well I think I'm done so far to the point where it does the exact same thing as the previous code, I would like to spend some time on batch sends though because the latest project I'll be using this in will have great use of that.

**Comment by wolfhechel** [comment]
Although I'd suggest bumping the major version instead because pushjack has no support for plaintext GCM notifications.

**Comment by rakanalh** [comment]
Batch sends would be great! However, i suggest keeping them in a different change set than py3 support. So if you're done with the py3 changes, let's have a look at the PR and merge it, then we can work on the batch sends and release them both together into a new major version.
In fact, V2 of django-pushy has been targeted to include py3 support if you remember our last discussion.
