### ISSUE TITLE
No support for JSON payloads with GCM

### ISSUE THREAD

**Issue by wolfhechel** [rakanalh/django-pushy#12]
Currently the GCM Dispatcher sends a plaintext request without the possibility to send a JSON payload, 
there should be a setting to choose.

**Comment by rakanalh** [comment]
As far as i am away, they both perform the same behaviour. Do you have a specific use-case?

**Comment by wolfhechel** [comment]
They do not, the plaintext request sends a POST form-data formatted payload, meaning a full JSON payload cannot fully be sent through a plaintext payload.
` {"number":1} ` for example fails to be sent due to the value not being a string.

Sending as a JSON payload sends the payload in the body of the request application/json as content-type.

**Comment by rakanalh** [comment]
I am still not sure why we need to worry about this given that using the "send_push_notification" util function will handle all the inner details for you. The only reason this would be justified is by having "automatic" parsing of JSON through Android by reading the content-type (if GCM forwards it which i am not really certain about). 

The current implementation will actually send a python dict {"number": 1} as  '{"number": 1}' which in the body of request.

Could you please explain me the real issue you're having with plaintext requests?

**Comment by wolfhechel** [comment]
As far as I can tell that's not what happens. 
The current implementation calls Gcm.plaintext_request with the dictionary payload,
plaintext_request in turn calls Gcm.make_request(payload, is_json=False), 
which in turn creates the appropriate request.

If is_json is true it dumps the payload as a JSON encoded string and sets Content-type to application/json.
If however is_json is False it uses the default Content-type which is application/x-www-form-urlencoded;charset=UTF-8 and passes the payload of to the function urlencode_utf8 (https://github.com/geeknam/python-gcm/blob/master/gcm/gcm.py#L78)

As you can see urlencode_utf8 iterates over the items in the payload and does a str().encode('utf-8') on both key and value of that dictionary, if the value is a number the function will fail since it's not encodeable.

That is the issue that I'm experiencing trying to send a nested dictionary with mixed boolean, numbers and string.

**Comment by rakanalh** [comment]
Makes sense. It's interesting enough that I am inclined to actually use this as a default behaviour rather then adding a new setting.

Can you modify your PR by removing the setting and making the request via request_json?

**Comment by wolfhechel** [comment]
I would rather see the JSON being used as default in that case and keep the option open for users, there's obviously a use-case else they would have deprecated the plaintext option long time ago.

**Comment by rakanalh** [comment]
Good point.

**Comment by wolfhechel** [comment]
I've changed the default behaviour now, I've left the tests with the previous default to send as plaintext to avoid having to rewrite them.

In the CHANGELOG you should also mention that the default behaviour has changed.
