### ISSUE TITLE
add task to processe APNS feedback

### ISSUE THREAD

**Issue by miraculixx** [rakanalh/django-pushy#22]
[apns](https://github.com/djacobs/PyAPNs) offers a feedback mechanism to get reports on bad device tockens. This should be automated so that invalid tokens can be deleted automatically (or better: marked as invalid so we can send users a reminder email):

```
#New APNS connection
feedback_connection = APNS(use_sandbox=True, cert_file='cert.pem', key_file='key.pem')

# Get feedback messages.
for (token_hex, fail_time) in feedback_connection.feedback_server.items():
    # get token, mark as invalid
```

Required changes:
- [ ] add status flag to `Device` with states `VALID`, `INVALID`
- [ ] add celery task based on the above code

Projects using `django-pushy` can then add this celery task as a daily scheduled task, thus automating device management.

**Comment by rakanalh** [comment]
Hi @miraculixx,

Great idea! you're very much welcome to send me a PR for this and i'll review and merge if this feature is needed on your end.

**Comment by wolfhechel** [comment]
I would rather have it delete the Device as is the default action taken when a device token is invalidated.

**Comment by rakanalh** [comment]
This has been implemented to delete the invalid token rather than keeping it.
PR: https://github.com/rakanalh/django-pushy/pull/41 which contains some refactorings also applies this.
