### ISSUE TITLE
Issue with latest migrations and MySQL

### ISSUE THREAD

**Issue by wolfhechel** [rakanalh/django-pushy#35]
When running the latest migrations in MySQL the DB backend raises
```
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'key' used in key specification without a key length")
``` 

This is due to Django ticket [7750](https://code.djangoproject.com/ticket/7750), which I take it won't be fixed.

An easy way to do it would be to change TextField() into CharField, problem is there's no real max length for GCM tokens, some developer claimed it could grow up to as large as 4096 bytes!

For now this is really breaking on PyPi as it's included in 0.1.10, so any ideas on how to approach this?

**Comment by rakanalh** [comment]
hmm, this is quite a surprise to be honest. However, the solution would be to have a CharField with the max length you've just described. I'll try to work something out very soon.
However, if you don't run migrate, is there anything else breaking when installing the package from pypi?

**Comment by wolfhechel** [comment]
No not as far as I can tell, I faked the migration for now on my own station and there's no complaining a part from that.. However my own development environment isn't configured to actually send notifications per say so I don't know yet that it works.
I'll know more once I've tried it in a configured staging environment.
