### ISSUE TITLE
Celery tasks should be decorated with celery.shared_task

### ISSUE THREAD

**Issue by wolfhechel** [rakanalh/django-pushy#7]
shared_task should be used for tasks in redistributable Django applications (as mentioned in [First steps with Django](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html))

**Comment by rakanalh** [comment]
Fair enough... will change it according to documentation

**Comment by wolfhechel** [comment]
I have the code ready for that, I'll make a pull request.
