### ISSUE TITLE
Default queue for tasks does not match celerys default queue

### ISSUE THREAD

**Issue by wolfhechel** [rakanalh/django-pushy#9]
I'm not sure if this is intentional, but when I first added the application to my project no tasks were dequeued. This is due to task decorators defaulting the queue to 'default'. Celerys default queue is in fact 'celery'.

**Comment by rakanalh** [comment]
That is true. You can either change the default queue name from the settings by adding:
```
PUSHY_QUEUE_DEFAULT_NAME = 'celery'
```
or start your workers on the default queue.

**Comment by wolfhechel** [comment]
That is true, however unless you had a specific reason behind the decision to default to 'default' I would suggest rather letting celery choose the default queue name by simply using None in the getattr calls instead of 'default'.

I think most people would expect the application to work without having to think about choosing the right queue for the tasks, a casual user of celery wouldn't even begin to bother with setting up multiple queues. Some might even be unaware that the queueing feature of Celery even exists.

**Comment by rakanalh** [comment]
hmm... good point. I'll re-open the issue, fix this and push a pip update today.
